export const defaultProducts = [
  {
    id: "yirgacheffe",
    name: "Yirgacheffe single origin",
    category: "Coffee",
    description: "Bright citrus, jasmine and a honeyed finish.",
    price: 18,
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=85",
    badge: "Bestseller",
  },
  {
    id: "house-blend",
    name: "House espresso blend",
    category: "Coffee",
    description: "A balanced, chocolatey daily cup with a silky body.",
    price: 16,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "sample-sidama-natural",
    name: "Sample coffee · Sidama natural",
    category: "Coffee",
    description: "Sample listing: a bright Ethiopian natural coffee profile. Edit the product, details, image, and price in Admin → Products before treating it as a real offer.",
    price: 18,
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=900&q=85",
    badge: "Sample",
    specifications: [
      { name: "Type", value: "Whole bean" },
      { name: "Roast level", value: "Light" },
      { name: "Taste type", value: "Fruity & floral" },
      { name: "Coffee tastes like", value: "Blueberry, citrus, jasmine" },
      { name: "Region", value: "Sidama" },
      { name: "Origin", value: "Ethiopia" },
      { name: "Process", value: "Natural (sample)" },
      { name: "Certification", value: "Not specified" },
      { name: "Roaster", value: "Nech Work sample" },
      { name: "Bag weight", value: "250 g" },
    ],
  },
  {
    id: "sample-yirgacheffe-washed",
    name: "Sample coffee · Yirgacheffe washed",
    category: "Coffee",
    description: "Sample listing: a clean, floral Ethiopian coffee profile. Confirm producer, processing, and product details before publishing as a real offer.",
    price: 20,
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=900&q=85",
    badge: "Sample",
    specifications: [
      { name: "Type", value: "Whole bean" },
      { name: "Roast level", value: "Light" },
      { name: "Taste type", value: "Floral & citrus" },
      { name: "Coffee tastes like", value: "Lemon, bergamot, tea" },
      { name: "Region", value: "Yirgacheffe" },
      { name: "Origin", value: "Ethiopia" },
      { name: "Process", value: "Washed (sample)" },
      { name: "Certification", value: "Not specified" },
      { name: "Roaster", value: "Nech Work sample" },
      { name: "Bag weight", value: "250 g" },
    ],
  },
  {
    id: "sample-guji-honey",
    name: "Sample coffee · Guji honey process",
    category: "Coffee",
    description: "Sample listing: a sweet, balanced Ethiopian coffee profile. Replace this placeholder copy with verified product information in the admin dashboard.",
    price: 19,
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=85",
    badge: "Sample",
    specifications: [
      { name: "Type", value: "Whole bean" },
      { name: "Roast level", value: "Medium" },
      { name: "Taste type", value: "Sweet & balanced" },
      { name: "Coffee tastes like", value: "Peach, honey, cocoa" },
      { name: "Region", value: "Guji" },
      { name: "Origin", value: "Ethiopia" },
      { name: "Process", value: "Honey (sample)" },
      { name: "Certification", value: "Not specified" },
      { name: "Roaster", value: "Nech Work sample" },
      { name: "Bag weight", value: "250 g" },
    ],
  },
  {
    id: "sample-harar-medium-roast",
    name: "Sample coffee · Harar medium roast",
    category: "Coffee",
    description: "Sample listing: a bold, fruit-forward Ethiopian coffee profile. Verify all product claims and replace sample details before sale.",
    price: 17,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=900&q=85",
    badge: "Sample",
    specifications: [
      { name: "Type", value: "Whole bean" },
      { name: "Roast level", value: "Medium" },
      { name: "Taste type", value: "Bold & fruity" },
      { name: "Coffee tastes like", value: "Berry, cocoa, spice" },
      { name: "Region", value: "Harar" },
      { name: "Origin", value: "Ethiopia" },
      { name: "Process", value: "Not specified" },
      { name: "Certification", value: "Not specified" },
      { name: "Roaster", value: "Nech Work sample" },
      { name: "Bag weight", value: "250 g" },
    ],
  },
  {
    id: "mountain-tea",
    name: "Mountain breakfast tea",
    category: "Tea",
    description: "A fragrant black tea blend for slow mornings.",
    price: 14,
    image: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?auto=format&fit=crop&w=900&q=85",
    badge: "New",
  },
  {
    id: "chai-spice",
    name: "Cardamom chai spice",
    category: "Tea",
    description: "Whole spices for a warm, aromatic cup at home.",
    price: 12,
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "wildflower-honey",
    name: "Wildflower honey",
    category: "Pantry",
    description: "Raw, small-batch honey with floral Ethiopian notes.",
    price: 11,
    image: "https://images.unsplash.com/photo-1471943311424-646960669fbc?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "sesame-crunch",
    name: "Sesame crunch",
    category: "Pantry",
    description: "Toasted sesame brittle made with local cane sugar.",
    price: 9,
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "ceramic-mug",
    name: "Hand-thrown stoneware mug",
    category: "Home & gifts",
    description: "A tactile, warm-grey mug made for your everyday ritual.",
    price: 28,
    image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "morning-box",
    name: "The slow morning box",
    category: "Home & gifts",
    description: "Coffee, honey and a mug, thoughtfully packed for gifting.",
    price: 52,
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85",
    badge: "Gift pick",
  },
];
